#### 1. Agrupamento de cortes transversais ao longo don tempo: métodos simples de dados em painel

O conjunto de códigos abaixo replica alguns exemplos práticos do Capítulo 13, intitulado "Agrupamento de cortes transversais ao longo do tempo: métodos simples de dados em painel", do livro Introdução à Econometria, tradução da 6º edição Norte Americana, do autor Jeffrey M. Wooldridge. Este capítulo aborda métodos simples de dados em painel que consiste em uma estrutura que combina informações de múltiplas unidades (como indivíduos, empresas ou países) observadas ao longo do tempo, permitindo capturar tanto variações entre unidades quanto dentro de uma mesma unidade ao longo do tempo. O livro, em formato digital e físico, pode ser adquirido no seguinte site: [amazon.com.br](https://www.amazon.com.br/Introdu%C3%A7%C3%A3o-%C3%A0-econometria-abordagem-moderna/dp/8522125643?ref_=ast_author_dp&dib=eyJ2IjoiMSJ9.xpLzGp_gZEtZm2kFmBCS0if6iw5aeB-m4qX1SKcoLrzW2xj1vkpOLp1CDoM7qPymZwglN1USzM69oUsMlZMlc8hm2kJEe2SLc4ft_i_GErH5YT2BZepNJLVH2D1cAGzU3WfbeyFYrMs4djQeG0V0I3MA2aVgo4IqjdGSKZzvuHkfd18qWqoBjSYovRqPNAU0sI9kwF6RwGG2EatJQ0LuUUOSw_OTKr29SeqG01Y7cds.zp4BJt5PaAnnWcFufRwtdk6xs-2WFdGq2UM5uH3Xrbc&dib_tag=AUTHOR).

### 2. Bibliotecas

In [1]:
# Manipulação dos dados
import pandas as pd
import numpy as np

# Estatística
import statsmodels.api as sm
import statsmodels.formula.api as smf

# Dados
import wooldridge as woo

# Configurações
import warnings

In [2]:
pd.set_option("display.max_columns", None)
pd.set_option("display.max_rows", None)
warnings.filterwarnings("ignore")

### Exemplo 13.1 - Fertilidade feminina ao longo do tempo

Questão de exemplo a ser repondida: após ter controlado a variável educação, o padrão de fertilidade entre mulheres com mias de 35 anos mudou entre 1972 e 1984? O seguinte exemplo ilustra como essa questão pode ser respondida de maneira mais simples, com o uso da análise de regressão múltipla com **variáveis dummy anuais**

In [3]:
# Importando os dados
fertil1 = woo.dataWoo('fertil1')

# primeiras observações
fertil1.head()

,year,educ,meduc,feduc,age,kids,black,east,northcen,west,farm,othrural,town,smcity,y74,y76,y78,y80,y82,y84,agesq,y74educ,y76educ,y78educ,y80educ,y82educ,y84educ
0,72,12,8,8,48,4,0,0,1,0,0,0,0,0,0,0,0,0,0,0,2304,0,0,0,0,0,0
1,72,17,8,18,46,3,0,0,0,0,0,1,0,0,0,0,0,0,0,0,2116,0,0,0,0,0,0
2,72,12,7,8,53,2,0,0,1,0,0,1,0,0,0,0,0,0,0,0,2809,0,0,0,0,0,0
3,72,12,12,10,42,2,0,0,1,0,0,0,1,0,0,0,0,0,0,0,1764,0,0,0,0,0,0
4,72,12,3,8,51,2,0,0,0,0,1,0,0,0,0,0,0,0,0,0,2601,0,0,0,0,0,0

In [4]:
# Formato dos dados
#fertil1.shape

In [5]:
# Dados faltantes por coluna
#fertil1.isna().sum()

Neste exemplo, o ano base é 1972. O coeficiente associado a y84 indica que, em comparação a 1972, no ano de 1984, as mulheres tiveram, em média, 0,54 filhos a menos. Isso significa que, mantendo todas as outras variáveis constantes, como educação, idade e outros fatores, um grupo de 100 mulheres em 1984 teria, em média, 54 filhos a menos do que um grupo semelhante de 100 mulheres em 1972.

In [6]:
# Variável dependente
y = fertil1["kids"]

# Variáveis independentes
X = fertil1[[
    "educ", "age", "agesq", "black", "east", "northcen", "west",
    "farm", "othrural", "town", "smcity", "y74", "y76", "y78", "y80", "y82", "y84"
]]

# Adicionando uma constante
X = sm.add_constant(X)

# Ajusta o MQO
model = sm.OLS(y, X).fit()

# Exibe os resultados
print(model.summary())

                            OLS Regression Results
==============================================================================
Dep. Variable:                   kids   R-squared:                       0.130
Model:                            OLS   Adj. R-squared:                  0.116
Method:                 Least Squares   F-statistic:                     9.723
Date:                Sat, 25 Jan 2025   Prob (F-statistic):           2.42e-24
Time:                        13:50:20   Log-Likelihood:                -2091.2
No. Observations:                1129   AIC:                             4218.
Df Residuals:                    1111   BIC:                             4309.
Df Model:                          17
Covariance Type:            nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const         -7.7425      3.052     -2.537      0.011     -13.730      -1.755
educ          -0.1284      0.018     -6.999      0.000      -0.164      -0.092
age            0.5321      0.138      3.845      0.000       0.261       0.804
agesq         -0.0058      0.002     -3.710      0.000      -0.009      -0.003
black          1.0757      0.174      6.198      0.000       0.735       1.416
east           0.2173      0.133      1.637      0.102      -0.043       0.478
northcen       0.3631      0.121      3.004      0.003       0.126       0.600
west           0.1976      0.167      1.184      0.237      -0.130       0.525
farm          -0.0526      0.147     -0.357      0.721      -0.341       0.236
othrural      -0.1629      0.175     -0.928      0.353      -0.507       0.181
town           0.0844      0.125      0.677      0.498      -0.160       0.329
smcity         0.2119      0.160      1.322      0.187      -0.103       0.526
y74            0.2682      0.173      1.553      0.121      -0.071       0.607
y76           -0.0974      0.179     -0.544      0.587      -0.449       0.254
y78           -0.0687      0.182     -0.378      0.706      -0.425       0.288
y80           -0.0713      0.183     -0.390      0.697      -0.430       0.287
y82           -0.5225      0.172     -3.030      0.003      -0.861      -0.184
y84           -0.5452      0.175     -3.124      0.002      -0.888      -0.203
==============================================================================
Omnibus:                        9.775   Durbin-Watson:                   2.011
Prob(Omnibus):                  0.008   Jarque-Bera (JB):                9.966
Skew:                           0.227   Prob(JB):                      0.00685
Kurtosis:                       2.920   Cond. No.                     1.32e+05
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 1.32e+05. This might indicate that there are
strong multicollinearity or other numerical problems.

### Exemplo 13.2 - Mudanças no retorno da educação e a diferença salarial por gênero

In [7]:
# Importando os dados
df = woo.dataWoo('cps78_85')

df.head()

,educ,south,nonwhite,female,married,exper,expersq,union,lwage,age,year,y85,y85fem,y85educ,y85union
0,12,0,0,0,0,8,64,0,1.2150,25,78,0,0,0,0
1,12,0,0,1,1,30,900,1,1.6094,47,78,0,0,0,0
2,6,0,0,0,1,38,1444,1,2.1401,49,78,0,0,0,0
3,12,0,0,0,1,19,361,1,2.0732,36,78,0,0,0,0
4,12,0,0,0,1,11,121,0,1.6490,28,78,0,0,0,0

In [8]:
# Verifica se há dados faltantes
#df.isna().sum()

Para o ano de 1978, cada ano adicional de educação implica, em média, um aumento de 7,47\% no salário. Já em 1985, o retorno de um ano adicional de educação sobre o salário foi 1,85\% maior em comparação ao ano base de 1972. Isso significa que, em 1985, o retorno total de um ano adicional de educação era de aproximadamente 9,35\%. Entretanto, o coeficiente y85 não é estatisticamente significativo.

In [9]:
# Variável dependente
y = df["lwage"]

# Variáveis independentes
X = df[[
       'y85', 'educ', 'y85educ','exper', 'expersq', 'union', 'female', 'y85fem' 
]]

# Adicionando uma constante
X = sm.add_constant(X)

# Ajusta o MQO
model = sm.OLS(y, X).fit()

# Exibe os resultados
print(model.summary())

                            OLS Regression Results
==============================================================================
Dep. Variable:                  lwage   R-squared:                       0.426
Model:                            OLS   Adj. R-squared:                  0.422
Method:                 Least Squares   F-statistic:                     99.80
Date:                Sat, 25 Jan 2025   Prob (F-statistic):          4.46e-124
Time:                        13:50:20   Log-Likelihood:                -574.24
No. Observations:                1084   AIC:                             1166.
Df Residuals:                    1075   BIC:                             1211.
Df Model:                           8
Covariance Type:            nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const          0.4589      0.093      4.911      0.000       0.276       0.642
y85            0.1178      0.124      0.952      0.341      -0.125       0.361
educ           0.0747      0.007     11.192      0.000       0.062       0.088
y85educ        0.0185      0.009      1.974      0.049       0.000       0.037
exper          0.0296      0.004      8.293      0.000       0.023       0.037
expersq       -0.0004   7.75e-05     -5.151      0.000      -0.001      -0.000
union          0.2021      0.030      6.672      0.000       0.143       0.262
female        -0.3167      0.037     -8.648      0.000      -0.389      -0.245
y85fem         0.0851      0.051      1.658      0.098      -0.016       0.186
==============================================================================
Omnibus:                       83.747   Durbin-Watson:                   1.918
Prob(Omnibus):                  0.000   Jarque-Bera (JB):              317.985
Skew:                          -0.271   Prob(JB):                     8.92e-70
Kurtosis:                       5.597   Cond. No.                     8.77e+03
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 8.77e+03. This might indicate that there are
strong multicollinearity or other numerical problems.

### Exemplo 13.3 - Efeito da localização de um incinerador de Lixo sobre os preços de imóveis

Exemplo a seguir: Estudo de um evento mostra como dois conjuntos de dados de cortes transversais, coletados antes e depois da ocorrência de um evento, podem ser usados para determinar seu  efeito sobre resultados econômicos. Kiel e McClain (1995) estudaram o efeito que um novo incinerador de lixo teve sobre os valore dos imóveis em North Andover, Massachusetts.

In [10]:
# Importando os dados
kielmc = woo.dataWoo('kielmc')

kielmc.head()

,year,age,agesq,nbh,cbd,intst,lintst,price,rooms,area,land,baths,dist,ldist,wind,lprice,y81,larea,lland,y81ldist,lintstsq,nearinc,y81nrinc,rprice,lrprice
0,1978,48,2304.0,4,3000.0,1000.0,6.9078,60000.0,7,1660,4578.0,1,10700.0,9.277999,3,11.002100,0,7.414573,8.429017,0.0,47.717705,1,0,60000.0,11.002100
1,1978,83,6889.0,4,4000.0,1000.0,6.9078,40000.0,6,2612,8370.0,2,11000.0,9.305651,3,10.596635,0,7.867871,9.032409,0.0,47.717705,1,0,40000.0,10.596635
2,1978,58,3364.0,4,4000.0,1000.0,6.9078,34000.0,6,1144,5000.0,1,11500.0,9.350102,3,10.434115,0,7.042286,8.517193,0.0,47.717705,1,0,34000.0,10.434115
3,1978,11,121.0,4,4000.0,1000.0,6.9078,63900.0,5,1136,10000.0,1,11900.0,9.384294,3,11.065075,0,7.035269,9.210340,0.0,47.717705,1,0,63900.0,11.065075
4,1978,48,2304.0,4,4000.0,2000.0,7.6009,44000.0,5,1868,10000.0,1,12100.0,9.400961,3,10.691945,0,7.532624,9.210340,0.0,57.773682,1,0,44000.0,10.691945

In [11]:
# Verificando se há dados faltantes
#kielmc.isna().sum()

Começaremos verificando o efeito monetário sobre os preços dos imóveis. Uma análise ingênua usaria somente os dados de 1981 e estimaria um modelo muito simples

In [12]:
kielmc81 = kielmc[kielmc['year'] == 1981]

In [13]:
# Variável dependente
y = kielmc81["rprice"]

# Variáveis independentes
X = kielmc81['nearinc']

# Adicionando uma constante
X = sm.add_constant(X)

# Ajusta o MQO
model = sm.OLS(y, X).fit()

# Exibe os resultados
print(model.summary())

                            OLS Regression Results
==============================================================================
Dep. Variable:                 rprice   R-squared:                       0.165
Model:                            OLS   Adj. R-squared:                  0.159
Method:                 Least Squares   F-statistic:                     27.73
Date:                Sat, 25 Jan 2025   Prob (F-statistic):           5.14e-07
Time:                        13:50:20   Log-Likelihood:                -1670.1
No. Observations:                 142   AIC:                             3344.
Df Residuals:                     140   BIC:                             3350.
Df Model:                           1
Covariance Type:            nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const       1.013e+05   3093.027     32.754      0.000    9.52e+04    1.07e+05
nearinc    -3.069e+04   5827.709     -5.266      0.000   -4.22e+04   -1.92e+04
==============================================================================
Omnibus:                       23.943   Durbin-Watson:                   1.380
Prob(Omnibus):                  0.000   Jarque-Bera (JB):               38.601
Skew:                           0.832   Prob(JB):                     4.15e-09
Kurtosis:                       4.939   Cond. No.                         2.44
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.

In [14]:
# Exibe os coeficientes e erros padrão com formatação não científica
print("Coeficientes:")
for param, coef in zip(model.params.index, model.params.values):
    print(f"{param}: {coef:,.2f}")

Coeficientes:
const: 101,307.51
nearinc: -30,688.27

A regressão acima não implica que a localização do incinerador esteja causando a queda nos valores dos imóveis. Na verdade, se rodarmos a mesma regressão para 1978 (antes mesmo de o incinerador ser cogitado), observamos que antes mesmo da instalação do incinerador no local definido os preços das casas já era menor nesta localidade.

In [15]:
kielmc78 = kielmc[kielmc['year'] == 1978]

In [16]:
# Variável dependente
y = kielmc78["rprice"]

# Variáveis independentes
X = kielmc78['nearinc']

# Adicionando uma constante
X = sm.add_constant(X)

# Ajusta o MQO
model = sm.OLS(y, X).fit()

# Exibe os resultados
print(model.summary())

                            OLS Regression Results
==============================================================================
Dep. Variable:                 rprice   R-squared:                       0.082
Model:                            OLS   Adj. R-squared:                  0.076
Method:                 Least Squares   F-statistic:                     15.74
Date:                Sat, 25 Jan 2025   Prob (F-statistic):           0.000105
Time:                        13:50:20   Log-Likelihood:                -2094.9
No. Observations:                 179   AIC:                             4194.
Df Residuals:                     177   BIC:                             4200.
Df Model:                           1
Covariance Type:            nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const       8.252e+04   2653.790     31.094      0.000    7.73e+04    8.78e+04
nearinc    -1.882e+04   4744.594     -3.968      0.000   -2.82e+04   -9461.117
==============================================================================
Omnibus:                      173.455   Durbin-Watson:                   1.707
Prob(Omnibus):                  0.000   Jarque-Bera (JB):             4526.710
Skew:                           3.520   Prob(JB):                         0.00
Kurtosis:                      26.609   Cond. No.                         2.42
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.

In [17]:
# Exibe os coeficientes e erros padrão com formatação não científica
print("Coeficientes:")
for param, coef in zip(model.params.index, model.params.values):
    print(f"{param}: {coef:,.2f}")

Coeficientes:
const: 82,517.23
nearinc: -18,824.37

Como, então, podemos determinar se a construção de um novo incinerador reduz os valores dos imóveis? A chave é observar como o coeficiente de nearinc mudou entre 1978 e 1981. A diferença no valor médio das casas foi muito maior em 1981 do que em 1978 (US 30.688,27 contra US 18.824,37), mesmo em termos percentuais em relação ao valor médio das casas distantes do local do incinerador. A diferença entre os dois coeficientes de nearinc é.

$$ \hat\delta_1 = -30.668,27 - (-18.824,37) = - 11.863,9$$

Essa é a estimativa do efeito do incinerador sobre os valores das casas próximas ao local do incinerador. Na economia aplicada, ficou conhecido como o, $ \hat\delta_1$, estimador de diferença em diferenças (DD ou DID) porque pode ser expresso como:

$$ \hat{\delta}_{1}=(\overline{rprice}_{81,nr}-\overline{price}_{81,fr})-(\overline{rprice}_{78,nr}-\overline{rprice}_{78,fr}) $$

Para testar $ \hat\delta_1$ se é estatisticamente diferente de zero, precisamos encontrar seu erro padrão utilizando uma análise de regressão. Na verdade, $ \hat\delta_1$, pode ser obtido estimando

$$ rprice = \beta_0 + \delta_0 \gamma_{81} + \beta_1 nearinc + \delta_1 \gamma_{81} \cdot nearinc + u $$

Estimando a regressão acima, que tmabém é a coluna (1) da tabela 13.2

In [18]:
# Variável dependente
y = kielmc["rprice"]

# Variáveis independentes
X = kielmc[['y81', 'nearinc', 'y81nrinc']]

# Adicionando uma constante
X = sm.add_constant(X)

# Ajusta o MQO
model = sm.OLS(y, X).fit()

# Exibe os resultados
print(model.summary())

                            OLS Regression Results
==============================================================================
Dep. Variable:                 rprice   R-squared:                       0.174
Model:                            OLS   Adj. R-squared:                  0.166
Method:                 Least Squares   F-statistic:                     22.25
Date:                Sat, 25 Jan 2025   Prob (F-statistic):           4.22e-13
Time:                        13:50:20   Log-Likelihood:                -3765.2
No. Observations:                 321   AIC:                             7538.
Df Residuals:                     317   BIC:                             7554.
Df Model:                           3
Covariance Type:            nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const       8.252e+04   2726.910     30.260      0.000    7.72e+04    8.79e+04
y81         1.879e+04   4050.065      4.640      0.000    1.08e+04    2.68e+04
nearinc    -1.882e+04   4875.322     -3.861      0.000   -2.84e+04   -9232.293
y81nrinc   -1.186e+04   7456.646     -1.591      0.113   -2.65e+04    2806.867
==============================================================================
Omnibus:                      192.562   Durbin-Watson:                   1.557
Prob(Omnibus):                  0.000   Jarque-Bera (JB):             2462.071
Skew:                           2.217   Prob(JB):                         0.00
Kurtosis:                      15.822   Cond. No.                         6.05
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.

In [19]:
# Exibe os coeficientes e erros padrão com formatação não científica
print("Coeficientes:")
for param, coef in zip(model.params.index, model.params.values):
    print(f"{param}: {coef:,.2f}")

Coeficientes:
const: 82,517.23
y81: 18,790.29
nearinc: -18,824.37
y81nrinc: -11,863.90

Abaixo, coluna (2) da tabela 13.2

In [20]:
# Variável dependente
y = kielmc["rprice"]

# Variáveis independentes
X = kielmc[['y81', 'nearinc', 'y81nrinc', 'age', 'agesq']]

# Adicionando uma constante
X = sm.add_constant(X)

# Ajusta o MQO
model = sm.OLS(y, X).fit()

# Exibe os resultados
print(model.summary())

                            OLS Regression Results
==============================================================================
Dep. Variable:                 rprice   R-squared:                       0.414
Model:                            OLS   Adj. R-squared:                  0.405
Method:                 Least Squares   F-statistic:                     44.59
Date:                Sat, 25 Jan 2025   Prob (F-statistic):           1.00e-34
Time:                        13:50:20   Log-Likelihood:                -3710.0
No. Observations:                 321   AIC:                             7432.
Df Residuals:                     315   BIC:                             7455.
Df Model:                           5
Covariance Type:            nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const       8.912e+04   2406.051     37.039      0.000    8.44e+04    9.39e+04
y81         2.132e+04   3443.631      6.191      0.000    1.45e+04    2.81e+04
nearinc     9397.9359   4812.222      1.953      0.052     -70.224    1.89e+04
y81nrinc   -2.192e+04   6359.745     -3.447      0.001   -3.44e+04   -9407.321
age        -1494.4240    131.860    -11.333      0.000   -1753.862   -1234.986
agesq          8.6913      0.848     10.248      0.000       7.023      10.360
==============================================================================
Omnibus:                      185.735   Durbin-Watson:                   1.668
Prob(Omnibus):                  0.000   Jarque-Bera (JB):             2674.532
Skew:                           2.062   Prob(JB):                         0.00
Kurtosis:                      16.526   Cond. No.                     2.66e+04
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 2.66e+04. This might indicate that there are
strong multicollinearity or other numerical problems.

In [21]:
# Exibe os coeficientes e erros padrão com formatação não científica
print("Coeficientes:")
for param, coef in zip(model.params.index, model.params.values):
    print(f"{param}: {coef:,.2f}")

Coeficientes:
const: 89,116.54
y81: 21,321.04
nearinc: 9,397.94
y81nrinc: -21,920.27
age: -1,494.42
agesq: 8.69

Abaixo, coluna (3) da tabela 13.2

In [22]:
# Variável dependente
y = kielmc["rprice"]

# Variáveis independentes
X = kielmc[['y81', 'nearinc', 'y81nrinc', 'age', 'agesq', 'intst', 'land', 'area', 'rooms', 'baths']]

# Adicionando uma constante
X = sm.add_constant(X)

# Ajusta o MQO
model = sm.OLS(y, X).fit()

# Exibe os resultados
print(model.summary())

                            OLS Regression Results
==============================================================================
Dep. Variable:                 rprice   R-squared:                       0.660
Model:                            OLS   Adj. R-squared:                  0.649
Method:                 Least Squares   F-statistic:                     60.19
Date:                Sat, 25 Jan 2025   Prob (F-statistic):           1.16e-66
Time:                        13:50:21   Log-Likelihood:                -3622.7
No. Observations:                 321   AIC:                             7267.
Df Residuals:                     310   BIC:                             7309.
Df Model:                          10
Covariance Type:            nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const       1.381e+04   1.12e+04      1.237      0.217   -8164.239    3.58e+04
y81         1.393e+04   2798.747      4.977      0.000    8421.533    1.94e+04
nearinc     3780.3368   4453.415      0.849      0.397   -4982.408    1.25e+04
y81nrinc   -1.418e+04   4987.267     -2.843      0.005    -2.4e+04   -4364.759
age         -739.4510    131.127     -5.639      0.000    -997.463    -481.439
agesq          3.4527      0.813      4.248      0.000       1.853       5.052
intst         -0.5386      0.196     -2.743      0.006      -0.925      -0.152
land           0.1414      0.031      4.551      0.000       0.080       0.203
area          18.0862      2.306      7.843      0.000      13.549      22.624
rooms       3304.2267   1661.248      1.989      0.048      35.479    6572.974
baths       6977.3166   2581.321      2.703      0.007    1898.191    1.21e+04
==============================================================================
Omnibus:                      120.913   Durbin-Watson:                   1.677
Prob(Omnibus):                  0.000   Jarque-Bera (JB):             1499.068
Skew:                           1.176   Prob(JB):                         0.00
Kurtosis:                      13.322   Cond. No.                     6.02e+05
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 6.02e+05. This might indicate that there are
strong multicollinearity or other numerical problems.

In [23]:
# Exibe os coeficientes e erros padrão com formatação não científica
print("Coeficientes:")
for param, coef in zip(model.params.index, model.params.values):
    print(f"{param}: {coef:,.2f}")

Coeficientes:
const: 13,807.67
y81: 13,928.48
nearinc: 3,780.34
y81nrinc: -14,177.93
age: -739.45
agesq: 3.45
intst: -0.54
land: 0.14
area: 18.09
rooms: 3,304.23
baths: 6,977.32

Agora, $ 100 . \delta_1 $ representa a redução percentual aproximada no valor das residências devido ao incinerador.

In [24]:
# Variável dependente
y = kielmc["lprice"]

# Variáveis independentes
X = kielmc[['y81', 'nearinc', 'y81nrinc']]

# Adicionando uma constante
X = sm.add_constant(X)

# Ajusta o MQO
model = sm.OLS(y, X).fit()

# Exibe os resultados
print(model.summary())

                            OLS Regression Results
==============================================================================
Dep. Variable:                 lprice   R-squared:                       0.409
Model:                            OLS   Adj. R-squared:                  0.403
Method:                 Least Squares   F-statistic:                     73.15
Date:                Sat, 25 Jan 2025   Prob (F-statistic):           5.61e-36
Time:                        13:50:22   Log-Likelihood:                -105.68
No. Observations:                 321   AIC:                             219.4
Df Residuals:                     317   BIC:                             234.4
Df Model:                           3
Covariance Type:            nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const         11.2854      0.031    369.839      0.000      11.225      11.345
y81            0.4570      0.045     10.084      0.000       0.368       0.546
nearinc       -0.3399      0.055     -6.231      0.000      -0.447      -0.233
y81nrinc      -0.0626      0.083     -0.751      0.453      -0.227       0.102
==============================================================================
Omnibus:                       29.462   Durbin-Watson:                   1.568
Prob(Omnibus):                  0.000   Jarque-Bera (JB):               84.380
Skew:                           0.370   Prob(JB):                     4.75e-19
Kurtosis:                       5.400   Cond. No.                         6.05
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.

O coeficiente do termo de interação implica que, devido ao novo incinerador, as casas próximas ao incinerador perderam cerca de 6,3% do seu valor. No entanto, essa estimativa não é estatisticamente diferente de zero. Mas quando usamos um conjunto completo de controles, como na coluna (3) da Tabela 13.2 (mas com intst, land e area aparecendo na forma logarítmica), o coeficiente de y81·nearinc se torna 2,132 com uma estatística t de cerca de 22,53. Novamente, controlar outros fatores se mostra importante. Usando a forma logarítmica, estimamos que as casas próximas ao incinerador foram desvalorizadas em cerca de 13,2%.

### Exemplo 13.4 - Efeitos das leis de indenizações trabalhistas sobre os prazos de afastamentos dos trabalhadores

Existe uma diferença entre o número de observações do exemplo utilizado no livro e o que está no código abaixo, o que gerou uma diferença dos valores estimados

In [25]:
# Importando os dados
injury = woo.dataWoo('injury')
injury.head()

,durat,afchnge,highearn,male,married,hosp,indust,injtype,age,prewage,totmed,injdes,benefit,ky,mi,ldurat,afhigh,lprewage,lage,ltotmed,head,neck,upextr,trunk,lowback,lowextr,occdis,manuf,construc,highlpre
0,1.0,1,1,1.0,0.0,1,3.0,1,26.0,404.950012,1187.573242,1010,246.837494,1,0,0.000000,1,6.003764,3.258096,7.079667,1,0,0,0,0,0,0,0.0,0.0,6.003764
1,1.0,1,1,1.0,1.0,0,3.0,1,31.0,643.825012,361.078552,1404,246.837494,1,0,0.000000,1,6.467427,3.433987,5.889095,1,0,0,0,0,0,0,0.0,0.0,6.467427
2,84.0,1,1,1.0,1.0,1,3.0,1,37.0,398.125000,8963.657227,1032,246.837494,1,0,4.430817,1,5.986766,3.610918,9.100934,1,0,0,0,0,0,0,0.0,0.0,5.986766
3,4.0,1,1,1.0,1.0,1,3.0,1,31.0,527.799988,1099.648315,1940,246.837494,1,0,1.386294,1,6.268717,3.433987,7.002746,1,0,0,0,0,0,0,0.0,0.0,6.268717
4,1.0,1,1,1.0,1.0,0,3.0,1,23.0,528.937500,372.801880,1940,211.574997,1,0,0.000000,1,6.270870,3.135494,5.921047,1,0,0,0,0,0,0,0.0,0.0,6.270870

In [26]:
# Verificando se há dados faltantes
injury.isna().sum()

durat         0
afchnge       0
highearn      0
male         16
married     297
hosp          0
indust       25
injtype       0
age           4
prewage       0
totmed        0
injdes        0
benefit       0
ky            0
mi            0
ldurat        0
afhigh        0
lprewage      0
lage          4
ltotmed       0
head          0
neck          0
upextr        0
trunk         0
lowback       0
lowextr       0
occdis        0
manuf        25
construc     25
highlpre      0
dtype: int64

In [27]:
# Removendo as observações faltantes
injury = injury.dropna()

In [28]:
# Criando a variável de interação
injury['afchnge_highearn'] = injury['afchnge']*injury['highearn']

In [34]:
# Variável dependente
y = injury["ldurat"]

# Variáveis independentes
X = injury[['afchnge', 'highearn', 'afchnge_highearn']]

# Adicionando uma constante
X = sm.add_constant(X)

# Ajusta o MQO
model = sm.OLS(y, X).fit()

# Exibe os resultados
print(model.summary())

                            OLS Regression Results
==============================================================================
Dep. Variable:                 ldurat   R-squared:                       0.016
Model:                            OLS   Adj. R-squared:                  0.016
Method:                 Least Squares   F-statistic:                     37.85
Date:                Sat, 25 Jan 2025   Prob (F-statistic):           3.01e-24
Time:                        16:41:14   Log-Likelihood:                -11425.
No. Observations:                6822   AIC:                         2.286e+04
Df Residuals:                    6818   BIC:                         2.288e+04
Df Model:                           3
Covariance Type:            nonrobust
====================================================================================
                       coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------------
const                1.2019      0.027     43.807      0.000       1.148       1.256
afchnge              0.0243      0.040      0.604      0.546      -0.055       0.103
highearn             0.1928      0.044      4.335      0.000       0.106       0.280
afchnge_highearn     0.2212      0.064      3.450      0.001       0.096       0.347
==============================================================================
Omnibus:                       52.733   Durbin-Watson:                   1.892
Prob(Omnibus):                  0.000   Jarque-Bera (JB):               79.931
Skew:                           0.046   Prob(JB):                     4.40e-18
Kurtosis:                       3.522   Cond. No.                         6.28
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.

### Exemplo 13.5 - Dormir versus trabalhar

Estimar a relação entre o tempo gasto dormindo e trabalhando. Exemplo explora a diferenciação.

In [35]:
# Importando os dados
slp75_81 = woo.dataWoo("slp75_81")
slp75_81.head()

,age75,educ75,educ81,gdhlth75,gdhlth81,male,marr75,marr81,slpnap75,slpnap81,totwrk75,totwrk81,yngkid75,yngkid81,ceduc,cgdhlth,cmarr,cslpnap,ctotwrk,cyngkid
0,46,16,16,1,1,1,0,1,3991,4695,2050,2430,0,0,0,0,1,704,380,0
1,39,16,16,1,1,1,1,0,2243,2195,2713,2610,0,0,0,0,-1,-48,-103,0
2,55,15,15,1,0,1,1,1,3285,3115,2493,0,0,0,0,-1,0,-170,-2493,0
3,39,16,16,1,1,1,1,1,3158,3387,2778,1787,0,0,0,0,0,229,-991,0
4,54,17,17,1,1,1,1,1,3743,3800,3118,552,0,0,0,0,0,57,-2566,0

In [33]:
# Verificando se há dados faltantes
#slp75_81.isna().sum()

In [38]:
# Calculando a primeira diferença para as variáveis de interesse
slp75_81['d_slpnap'] = slp75_81['slpnap81'] - slp75_81['slpnap75']
slp75_81['d_totwrk'] = slp75_81['totwrk81'] - slp75_81['totwrk75']
slp75_81['d_educ'] = slp75_81['educ81'] - slp75_81['educ75']
slp75_81['d_marr'] = slp75_81['marr81'] - slp75_81['marr75']
slp75_81['d_yngkid'] = slp75_81['yngkid81'] - slp75_81['yngkid75']
slp75_81['d_gdhlth'] = slp75_81['gdhlth81'] - slp75_81['gdhlth75']

In [39]:
# Variável dependente
y = slp75_81["d_slpnap"]

# Variáveis independentes
X = slp75_81[['d_totwrk', 'd_educ', 'd_marr', 'd_yngkid', 'd_gdhlth']]

# Adicionando uma constante
X = sm.add_constant(X)

# Ajusta o MQO
model = sm.OLS(y, X).fit()

# Exibe os resultados
print(model.summary())

                            OLS Regression Results
==============================================================================
Dep. Variable:               d_slpnap   R-squared:                       0.150
Model:                            OLS   Adj. R-squared:                  0.131
Method:                 Least Squares   F-statistic:                     8.191
Date:                Sat, 25 Jan 2025   Prob (F-statistic):           3.83e-07
Time:                        16:50:58   Log-Likelihood:                -1864.4
No. Observations:                 239   AIC:                             3741.
Df Residuals:                     233   BIC:                             3762.
Df Model:                           5
Covariance Type:            nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const        -92.6340     45.866     -2.020      0.045    -182.999      -2.269
d_totwrk      -0.2267      0.036     -6.287      0.000      -0.298      -0.156
d_educ        -0.0245     48.759     -0.001      1.000     -96.090      96.041
d_marr       104.2139     92.855      1.122      0.263     -78.729     287.157
d_yngkid      94.6654     87.653      1.080      0.281     -78.027     267.358
d_gdhlth      87.5778     76.599      1.143      0.254     -63.338     238.493
==============================================================================
Omnibus:                       31.927   Durbin-Watson:                   1.890
Prob(Omnibus):                  0.000   Jarque-Bera (JB):               57.378
Skew:                          -0.719   Prob(JB):                     3.47e-13
Kurtosis:                       4.922   Cond. No.                     2.72e+03
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 2.72e+03. This might indicate that there are
strong multicollinearity or other numerical problems.

### Exemplo 13.6 - Defasagens distribuídas da taxa de criminalidade sobre a taxa de esclarecimento de crimes

Exemplo: defasando a única variável independente em 1 e dois anos é possível verificar se as taxas de esclarecimentos dos crimes do passado tenham efeito dissuasor sobre a criminalidade atual ?

In [63]:
# Importando os dados
crime3 = woo.dataWoo('crime3')
crime3.head()

,district,year,crime,clrprc1,clrprc2,d78,avgclr,lcrime,clcrime,cavgclr,cclrprc1,cclrprc2
0,1,72,49.540001,22,23,0,22.5,3.902781,NaN,NaN,NaN,NaN
1,1,78,71.320000,15,17,1,16.0,4.267177,0.364396,-6.5,-7.0,-6.0
2,2,72,14.770000,51,62,0,56.5,2.692598,NaN,NaN,NaN,NaN
3,2,78,17.850000,39,40,1,39.5,2.882004,0.189405,-17.0,-12.0,-22.0
4,3,72,17.350000,33,34,0,33.5,2.853593,NaN,NaN,NaN,NaN

In [64]:
# Computando a primeira diferença
crime3['Dlog_crime'] = crime3['lcrime'].diff()
crime3['Dclrprc1'] = crime3['clrprc1'].diff()
crime3['Dclrprc2'] = crime3['clrprc2'].diff()

In [65]:
# Verificando quantos são os dados faltantes
crime3.isna().sum()

district       0
year           0
crime          0
clrprc1        0
clrprc2        0
d78            0
avgclr         0
lcrime         0
clcrime       53
cavgclr       53
cclrprc1      53
cclrprc2      53
Dlog_crime     1
Dclrprc1       1
Dclrprc2       1
dtype: int64

In [66]:
# Removendo os dados faltantes
crime3 = crime3.dropna()

In [67]:
# Variável dependente
y = crime3["Dlog_crime"]

# Variáveis independentes
X = crime3[['Dclrprc1', 'Dclrprc2']]

# Adicionando uma constante
X = sm.add_constant(X)

# Ajusta o MQO
model = sm.OLS(y, X).fit()

# Exibe os resultados
print(model.summary())

                            OLS Regression Results
==============================================================================
Dep. Variable:             Dlog_crime   R-squared:                       0.193
Model:                            OLS   Adj. R-squared:                  0.161
Method:                 Least Squares   F-statistic:                     5.992
Date:                Sat, 25 Jan 2025   Prob (F-statistic):            0.00465
Time:                        17:16:28   Log-Likelihood:                -17.194
No. Observations:                  53   AIC:                             40.39
Df Residuals:                      50   BIC:                             46.30
Df Model:                           2
Covariance Type:            nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const          0.0857      0.064      1.343      0.185      -0.042       0.214
Dclrprc1      -0.0040      0.005     -0.858      0.395      -0.014       0.005
Dclrprc2      -0.0132      0.005     -2.540      0.014      -0.024      -0.003
==============================================================================
Omnibus:                        3.032   Durbin-Watson:                   2.203
Prob(Omnibus):                  0.220   Jarque-Bera (JB):                2.071
Skew:                          -0.344   Prob(JB):                        0.355
Kurtosis:                       3.681   Cond. No.                         23.6
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.

### Exemplo 13.7 - Efeitos da legislação a respeito da condução de veículos sob embriaguez sobre as fatalidades no trânsito

In [71]:
# Importando os dados
traffic1 = woo.dataWoo('traffic1')
traffic1.head()

,state,admn90,admn85,open90,open85,dthrte90,dthrte85,speed90,speed85,cdthrte,cadmn,copen,cspeed
0,AL,0,0,0,0,2.6,2.9,1,0,-0.3,0,0,1
1,AK,1,1,1,0,2.1,3.2,0,0,-1.1,0,1,0
2,AZ,1,0,0,0,2.5,4.4,1,0,-1.9,1,0,1
3,AR,0,0,0,0,2.9,3.4,1,0,-0.5,0,0,1
4,CA,1,0,1,1,2.0,2.6,1,0,-0.6,1,0,1

In [73]:
# Formato dos dados
traffic1.shape

(51, 13)

In [72]:
# Verificando os dados faltantes
#traffic1.isna().sum()

state       0
admn90      0
admn85      0
open90      0
open85      0
dthrte90    0
dthrte85    0
speed90     0
speed85     0
cdthrte     0
cadmn       0
copen       0
cspeed      0
dtype: int64

O df traffic1 comtém dados de 1985 e 1990 de todos os 50 estados norte-americanos e do Distrito de Colúmbia. A variável dependente é o número de mortes de trânsito por 100 milhões de milhas (dthrte). Em 1985, 19 estados tinham leis de recipientes abertos, enquanto 22 estados tinham essas leis em 1990. Em 1985, 21 estados tinham leis administrativas propriamente ditas; esse número subii para 29 em 1990. O uso de MQO após a primeira diferença produz:

In [75]:
traffic1.columns

Index(['state', 'admn90', 'admn85', 'open90', 'open85', 'dthrte90', 'dthrte85',
       'speed90', 'speed85', 'cdthrte', 'cadmn', 'copen', 'cspeed'],
      dtype='object')

In [76]:
traffic1['d_dthrte'] = traffic1['dthrte90'] - traffic1['dthrte85']
traffic1['d_open'] = traffic1['open90'] - traffic1['open85']
traffic1['d_admn'] = traffic1['admn90'] - traffic1['admn85']

In [78]:
# Variável dependente
y = traffic1["d_dthrte"]

# Variáveis independentes
X = traffic1[['d_open', 'd_admn']]

# Adicionando uma constante
X = sm.add_constant(X)

# Ajusta o MQO
model = sm.OLS(y, X).fit()

# Exibe os resultados
print(model.summary())

                            OLS Regression Results
==============================================================================
Dep. Variable:               d_dthrte   R-squared:                       0.119
Model:                            OLS   Adj. R-squared:                  0.082
Method:                 Least Squares   F-statistic:                     3.231
Date:                Sat, 25 Jan 2025   Prob (F-statistic):             0.0482
Time:                        17:58:00   Log-Likelihood:                -16.323
No. Observations:                  51   AIC:                             38.65
Df Residuals:                      48   BIC:                             44.44
Df Model:                           2
Covariance Type:            nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const         -0.4968      0.052     -9.476      0.000      -0.602      -0.391
d_open        -0.4197      0.206     -2.041      0.047      -0.833      -0.006
d_admn        -0.1506      0.117     -1.289      0.204      -0.385       0.084
==============================================================================
Omnibus:                       17.834   Durbin-Watson:                   2.412
Prob(Omnibus):                  0.000   Jarque-Bera (JB):               30.963
Skew:                          -1.037   Prob(JB):                     1.89e-07
Kurtosis:                       6.205   Cond. No.                         4.36
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.

### Exemplo 13.9 - Taxas de criminalidade municipais na Carolina do Norte

In [91]:
# Importando os dados
crime4 = woo.dataWoo("crime4")
crime4.head()

,county,year,crmrte,prbarr,prbconv,prbpris,avgsen,polpc,density,taxpc,west,central,urban,pctmin80,wcon,wtuc,wtrd,wfir,wser,wmfg,wfed,wsta,wloc,mix,pctymle,d82,d83,d84,d85,d86,d87,lcrmrte,lprbarr,lprbconv,lprbpris,lavgsen,lpolpc,ldensity,ltaxpc,lwcon,lwtuc,lwtrd,lwfir,lwser,lwmfg,lwfed,lwsta,lwloc,lmix,lpctymle,lpctmin,clcrmrte,clprbarr,clprbcon,clprbpri,clavgsen,clpolpc,cltaxpc,clmix
0,1,81,0.039885,0.289696,0.402062,0.472222,5.61,0.001787,2.307159,25.697630,0,1,0,20.2187,206.480301,333.620880,182.333008,272.449188,215.733490,229.119995,409.369995,236.240005,231.470001,0.099918,0.087697,0,0,0,0,0,0,-3.221757,-1.238923,-0.911149,-0.750306,1.724551,-6.327340,0.836017,3.246399,5.330205,5.810005,5.205835,5.607452,5.374044,5.434246,6.014619,5.464848,5.444450,-2.303407,-2.433870,3.006608,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1,82,0.038345,0.338111,0.433005,0.506993,5.59,0.001767,2.330254,24.874252,0,1,0,20.2187,212.754196,369.296417,189.541412,300.878754,231.576706,240.330002,419.700012,253.880005,236.789993,0.103049,0.086377,1,0,0,0,0,0,-3.261134,-1.084381,-0.837006,-0.679258,1.720979,-6.338704,0.845977,3.213833,5.360137,5.911600,5.244607,5.706707,5.444911,5.482013,6.039540,5.536862,5.467174,-2.272549,-2.449038,3.006608,-0.039376,0.154542,0.074143,0.071048,-0.003571,-0.011364,-0.032565,0.030857
2,1,83,0.030305,0.330449,0.525703,0.479705,5.80,0.001836,2.341801,26.451443,0,1,0,20.2187,219.780212,1394.803467,196.639465,309.969635,240.156845,269.700012,438.850006,250.360001,248.580002,0.080679,0.085091,0,1,0,0,0,0,-3.496449,-1.107303,-0.643019,-0.734584,1.757858,-6.300291,0.850920,3.275311,5.392628,7.240509,5.281372,5.736475,5.481292,5.597310,6.084157,5.522900,5.515765,-2.517281,-2.464036,3.006608,-0.235316,-0.022922,0.193987,-0.055326,0.036879,0.038413,0.061477,-0.244732
3,1,84,0.034726,0.362525,0.604706,0.520104,6.89,0.001886,2.346420,26.842348,0,1,0,20.2187,223.423798,398.860413,200.562912,350.086334,252.447678,281.739990,459.170013,261.929993,264.380005,0.078504,0.083833,0,0,1,0,0,0,-3.360270,-1.014662,-0.503013,-0.653727,1.930071,-6.273361,0.852891,3.289981,5.409070,5.988612,5.301128,5.858180,5.531204,5.640985,6.129421,5.568077,5.577387,-2.544612,-2.478925,3.006608,0.136180,0.092641,0.140006,0.080857,0.172213,0.026930,0.014670,-0.027331
4,1,85,0.036573,0.325395,0.578723,0.497059,6.55,0.001924,2.364896,28.140337,0,1,0,20.2187,243.756241,358.783020,206.882736,383.070740,261.086121,298.880005,490.429993,281.440002,288.579987,0.093249,0.082306,0,0,0,1,0,0,-3.308445,-1.122715,-0.546931,-0.699047,1.879465,-6.253162,0.860734,3.337204,5.496169,5.882718,5.332152,5.948220,5.564850,5.700042,6.195282,5.639919,5.664972,-2.372487,-2.497306,3.006608,0.051825,-0.108054,-0.043918,-0.045320,-0.050606,0.020199,0.047223,0.172125

In [92]:
# Verificando se há dados faltantes
#crime4.isna().sum()

In [95]:
import numpy as np
import linearmodels as plm

crime4 = crime4.set_index(['county', 'year'], drop=False)

# estimate FD model:
reg = plm.FirstDifferenceOLS.from_formula(
    formula='np.log(crmrte) ~ year + d83 + d84 + d85 + d86 + d87 +'
            'lprbarr + lprbconv + lprbpris + lavgsen + lpolpc',
    data=crime4)
results = reg.fit()
print(f'results: \n{results}\n')

results:
                     FirstDifferenceOLS Estimation Summary
================================================================================
Dep. Variable:         np.log(crmrte)   R-squared:                        0.4326
Estimator:         FirstDifferenceOLS   R-squared (Between):              0.6003
No. Observations:                 540   R-squared (Within):               0.4281
Date:                Sat, Jan 25 2025   R-squared (Overall):              0.6000
Time:                        19:34:31   Log-likelihood                    248.48
Cov. Estimator:            Unadjusted
                                        F-statistic:                      36.661
Entities:                          90   P-value                           0.0000
Avg Obs:                       7.0000   Distribution:                  F(11,529)
Min Obs:                       7.0000
Max Obs:                       7.0000   F-statistic (robust):             36.661
                                        P-value                           0.0000
Time periods:                       7   Distribution:                  F(11,529)
Avg Obs:                       90.000
Min Obs:                       90.000
Max Obs:                       90.000

                             Parameter Estimates
==============================================================================
            Parameter  Std. Err.     T-stat    P-value    Lower CI    Upper CI
------------------------------------------------------------------------------
year           0.0077     0.0171     0.4522     0.6513     -0.0258      0.0412
d83           -0.0999     0.0239    -4.1793     0.0000     -0.1468     -0.0529
d84           -0.1478     0.0413    -3.5806     0.0004     -0.2289     -0.0667
d85           -0.1524     0.0584    -2.6098     0.0093     -0.2671     -0.0377
d86           -0.1249     0.0760    -1.6433     0.1009     -0.2742      0.0244
d87           -0.0841     0.0940    -0.8944     0.3715     -0.2687      0.1006
lprbarr       -0.3275     0.0300    -10.924     0.0000     -0.3864     -0.2686
lprbconv      -0.2381     0.0182    -13.058     0.0000     -0.2739     -0.2023
lprbpris      -0.1650     0.0260    -6.3555     0.0000     -0.2161     -0.1140
lavgsen       -0.0218     0.0221    -0.9850     0.3251     -0.0652      0.0216
lpolpc         0.3984     0.0269     14.821     0.0000      0.3456      0.4512
==============================================================================