### 1. Métodos avançados de dados em painel

O conjunto de códigos abaixo replica alguns exemplos práticos do Capítulo 14, intitulado "Métodos avançados de dados em painel", do livro Introdução à Econometria, tradução da 6º edição Norte Americana, do autor Jeffrey M. Wooldridge. Este capítulo aborda métodos um pouco mais avançados de dados em painel, como o estimador de efeitos fixos e a abordagem de efeitos aleatórios. O livro, em formato digital e físico, pode ser adquirido no seguinte site: [amazon.com.br](https://www.amazon.com.br/Introdu%C3%A7%C3%A3o-%C3%A0-econometria-abordagem-moderna/dp/8522125643?ref_=ast_author_dp&dib=eyJ2IjoiMSJ9.xpLzGp_gZEtZm2kFmBCS0if6iw5aeB-m4qX1SKcoLrzW2xj1vkpOLp1CDoM7qPymZwglN1USzM69oUsMlZMlc8hm2kJEe2SLc4ft_i_GErH5YT2BZepNJLVH2D1cAGzU3WfbeyFYrMs4djQeG0V0I3MA2aVgo4IqjdGSKZzvuHkfd18qWqoBjSYovRqPNAU0sI9kwF6RwGG2EatJQ0LuUUOSw_OTKr29SeqG01Y7cds.zp4BJt5PaAnnWcFufRwtdk6xs-2WFdGq2UM5uH3Xrbc&dib_tag=AUTHOR).

### 2. Bibliotecas

In [69]:
# Manipulação dos dados
import pandas as pd

# Estatística
from linearmodels.panel import PanelOLS

# Dados
import wooldridge as woo

# Configurações
import warnings

In [70]:
pd.set_option("display.max_columns", None)
pd.set_option("display.max_rows", None)
warnings.filterwarnings("ignore")

### Exemplo 14.1 - Efeito do treinamento de pessoal sobre as taxas de refugos de produtos das empresas

Estimando um modelo de efeitos não observados por efeitos fixos.

In [71]:
# Importando os dados
jtrain = woo.dataWoo("jtrain")
jtrain.head()

,year,fcode,employ,sales,avgsal,scrap,rework,tothrs,union,grant,d89,d88,totrain,hrsemp,lscrap,lemploy,lsales,lrework,lhrsemp,lscrap_1,grant_1,clscrap,cgrant,clemploy,clsales,lavgsal,clavgsal,cgrant_1,chrsemp,clhrsemp
0,1987,410032.0,100.0,47000000.0,35000.0,NaN,NaN,12.0,0,0,0,0,100.0,12.000000,NaN,4.605170,17.665659,NaN,2.564949,NaN,0,NaN,0,NaN,NaN,10.463103,NaN,NaN,NaN,NaN
1,1988,410032.0,131.0,43000000.0,37000.0,NaN,NaN,8.0,0,0,0,1,50.0,3.053435,NaN,4.875197,17.576710,NaN,1.399565,NaN,0,NaN,0,0.270027,-0.088949,10.518673,0.055570,0.0,-8.946565,-1.165385
2,1989,410032.0,123.0,49000000.0,39000.0,NaN,NaN,8.0,0,0,1,0,50.0,3.252033,NaN,4.812184,17.707331,NaN,1.447397,NaN,0,NaN,0,-0.063013,0.130621,10.571317,0.052644,0.0,0.198597,0.047832
3,1987,410440.0,12.0,1560000.0,10500.0,NaN,NaN,12.0,0,0,0,0,12.0,12.000000,NaN,2.484907,14.260197,NaN,2.564949,NaN,0,NaN,0,NaN,NaN,9.259130,NaN,NaN,NaN,NaN
4,1988,410440.0,13.0,1970000.0,11000.0,NaN,NaN,12.0,0,0,0,1,13.0,12.000000,NaN,2.564949,14.493544,NaN,2.564949,NaN,0,NaN,0,0.080043,0.233347,9.305651,0.046520,0.0,0.000000,0.000000

In [72]:
# Formato dos dados
jtrain.shape

(471, 30)

In [73]:
# Dados faltantes por coluna
#jtrain.isna().mean()

In [74]:
# Ajustando os índices (ano e identificador)
jtrain = jtrain.set_index(['fcode', 'year'])

In [75]:
jtrain.head()

               employ       sales   avgsal  scrap  rework  tothrs  union  \
fcode    year
410032.0 1987   100.0  47000000.0  35000.0    NaN     NaN    12.0      0
         1988   131.0  43000000.0  37000.0    NaN     NaN     8.0      0
         1989   123.0  49000000.0  39000.0    NaN     NaN     8.0      0
410440.0 1987    12.0   1560000.0  10500.0    NaN     NaN    12.0      0
         1988    13.0   1970000.0  11000.0    NaN     NaN    12.0      0

               grant  d89  d88  totrain     hrsemp  lscrap   lemploy  \
fcode    year
410032.0 1987      0    0    0    100.0  12.000000     NaN  4.605170
         1988      0    0    1     50.0   3.053435     NaN  4.875197
         1989      0    1    0     50.0   3.252033     NaN  4.812184
410440.0 1987      0    0    0     12.0  12.000000     NaN  2.484907
         1988      0    0    1     13.0  12.000000     NaN  2.564949

                  lsales  lrework   lhrsemp  lscrap_1  grant_1  clscrap  \
fcode    year
410032.0 1987  17.665659      NaN  2.564949       NaN        0      NaN
         1988  17.576710      NaN  1.399565       NaN        0      NaN
         1989  17.707331      NaN  1.447397       NaN        0      NaN
410440.0 1987  14.260197      NaN  2.564949       NaN        0      NaN
         1988  14.493544      NaN  2.564949       NaN        0      NaN

               cgrant  clemploy   clsales    lavgsal  clavgsal  cgrant_1  \
fcode    year
410032.0 1987       0       NaN       NaN  10.463103       NaN       NaN
         1988       0  0.270027 -0.088949  10.518673  0.055570       0.0
         1989       0 -0.063013  0.130621  10.571317  0.052644       0.0
410440.0 1987       0       NaN       NaN   9.259130       NaN       NaN
         1988       0  0.080043  0.233347   9.305651  0.046520       0.0

                chrsemp  clhrsemp
fcode    year
410032.0 1987       NaN       NaN
         1988 -8.946565 -1.165385
         1989  0.198597  0.047832
410440.0 1987       NaN       NaN
         1988  0.000000  0.000000

In [76]:
# Regressão
model = PanelOLS.from_formula('lscrap ~ d88 + d89 + grant + grant_1 + EntityEffects', data=jtrain)
results = model.fit()

# Exibindo resultados
print(results.summary)

                          PanelOLS Estimation Summary
================================================================================
Dep. Variable:                 lscrap   R-squared:                        0.2010
Estimator:                   PanelOLS   R-squared (Between):             -0.1103
No. Observations:                 162   R-squared (Within):               0.2010
Date:                Mon, Jan 27 2025   R-squared (Overall):             -0.0839
Time:                        16:51:32   Log-likelihood                   -80.946
Cov. Estimator:            Unadjusted
                                        F-statistic:                      6.5426
Entities:                          54   P-value                           0.0001
Avg Obs:                       3.0000   Distribution:                   F(4,104)
Min Obs:                       3.0000
Max Obs:                       3.0000   F-statistic (robust):             6.5426
                                        P-value                           0.0001
Time periods:                       3   Distribution:                   F(4,104)
Avg Obs:                       54.000
Min Obs:                       54.000
Max Obs:                       54.000

                             Parameter Estimates
==============================================================================
            Parameter  Std. Err.     T-stat    P-value    Lower CI    Upper CI
------------------------------------------------------------------------------
d88           -0.0802     0.1095    -0.7327     0.4654     -0.2973      0.1369
d89           -0.2472     0.1332    -1.8556     0.0663     -0.5114      0.0170
grant         -0.2523     0.1506    -1.6751     0.0969     -0.5510      0.0464
grant_1       -0.4216     0.2102    -2.0057     0.0475     -0.8384     -0.0048
==============================================================================

F-test for Poolability: 24.661
P-value: 0.0000
Distribution: F(53,104)

Included effects: Entity

### Exemplo 14.2 - O retorno da educação mudou no transcorrer do tempo ?

In [77]:
# Importando os dados
wagepan = woo.dataWoo("wagepan")
wagepan.head()

,nr,year,agric,black,bus,construc,ent,exper,fin,hisp,poorhlth,hours,manuf,married,min,nrthcen,nrtheast,occ1,occ2,occ3,occ4,occ5,occ6,occ7,occ8,occ9,per,pro,pub,rur,south,educ,tra,trad,union,lwage,d81,d82,d83,d84,d85,d86,d87,expersq
0,13,1980,0,0,1,0,0,1,0,0,0,2672,0,0,0,0,1,0,0,0,0,0,0,0,0,1,0,0,0,0,0,14,0,0,0,1.197540,0,0,0,0,0,0,0,1
1,13,1981,0,0,0,0,0,2,0,0,0,2320,0,0,0,0,1,0,0,0,0,0,0,0,0,1,1,0,0,0,0,14,0,0,1,1.853060,1,0,0,0,0,0,0,4
2,13,1982,0,0,1,0,0,3,0,0,0,2940,0,0,0,0,1,0,0,0,0,0,0,0,0,1,0,0,0,0,0,14,0,0,0,1.344462,0,1,0,0,0,0,0,9
3,13,1983,0,0,1,0,0,4,0,0,0,2960,0,0,0,0,1,0,0,0,0,0,0,0,0,1,0,0,0,0,0,14,0,0,0,1.433213,0,0,1,0,0,0,0,16
4,13,1984,0,0,0,0,0,5,0,0,0,3071,0,0,0,0,1,0,0,0,0,1,0,0,0,0,1,0,0,0,0,14,0,0,0,1.568125,0,0,0,1,0,0,0,25

In [78]:
# Formato dos dados
wagepan.shape

(4360, 44)

In [79]:
# Dados faltantes
# wagepan.isna().sum()

In [80]:
# Ajustando os índices (ano e identificador)
wagepan = wagepan.set_index(['nr', 'year'], drop=False)

In [81]:
wagepan.head()

         nr  year  agric  black  bus  construc  ent  exper  fin  hisp  \
nr year
13 1980  13  1980      0      0    1         0    0      1    0     0
   1981  13  1981      0      0    0         0    0      2    0     0
   1982  13  1982      0      0    1         0    0      3    0     0
   1983  13  1983      0      0    1         0    0      4    0     0
   1984  13  1984      0      0    0         0    0      5    0     0

         poorhlth  hours  manuf  married  min  nrthcen  nrtheast  occ1  occ2  \
nr year
13 1980         0   2672      0        0    0        0         1     0     0
   1981         0   2320      0        0    0        0         1     0     0
   1982         0   2940      0        0    0        0         1     0     0
   1983         0   2960      0        0    0        0         1     0     0
   1984         0   3071      0        0    0        0         1     0     0

         occ3  occ4  occ5  occ6  occ7  occ8  occ9  per  pro  pub  rur  south  \
nr year
13 1980     0     0     0     0     0     0     1    0    0    0    0      0
   1981     0     0     0     0     0     0     1    1    0    0    0      0
   1982     0     0     0     0     0     0     1    0    0    0    0      0
   1983     0     0     0     0     0     0     1    0    0    0    0      0
   1984     0     0     1     0     0     0     0    1    0    0    0      0

         educ  tra  trad  union     lwage  d81  d82  d83  d84  d85  d86  d87  \
nr year
13 1980    14    0     0      0  1.197540    0    0    0    0    0    0    0
   1981    14    0     0      1  1.853060    1    0    0    0    0    0    0
   1982    14    0     0      0  1.344462    0    1    0    0    0    0    0
   1983    14    0     0      0  1.433213    0    0    1    0    0    0    0
   1984    14    0     0      0  1.568125    0    0    0    1    0    0    0

         expersq
nr year
13 1980        1
   1981        4
   1982        9
   1983       16
   1984       25

In [82]:
# Regressão
model = PanelOLS.from_formula('lwage ~ married + union + C(year)*educ + EntityEffects', data=wagepan, drop_absorbed=True)
results = model.fit()

# Exibindo resultados
print(results.summary)

                          PanelOLS Estimation Summary
================================================================================
Dep. Variable:                  lwage   R-squared:                        0.1708
Estimator:                   PanelOLS   R-squared (Between):              0.0905
No. Observations:                4360   R-squared (Within):               0.1708
Date:                Mon, Jan 27 2025   R-squared (Overall):              0.1277
Time:                        16:51:38   Log-likelihood                   -1350.7
Cov. Estimator:            Unadjusted
                                        F-statistic:                      48.907
Entities:                         545   P-value                           0.0000
Avg Obs:                       8.0000   Distribution:                 F(16,3799)
Min Obs:                       8.0000
Max Obs:                       8.0000   F-statistic (robust):             5454.7
                                        P-value                           0.0000
Time periods:                       8   Distribution:                 F(16,3799)
Avg Obs:                       545.00
Min Obs:                       545.00
Max Obs:                       545.00

                                  Parameter Estimates
========================================================================================
                      Parameter  Std. Err.     T-stat    P-value    Lower CI    Upper CI
----------------------------------------------------------------------------------------
married                  0.0548     0.0184     2.9773     0.0029      0.0187      0.0909
union                    0.0830     0.0194     4.2671     0.0000      0.0449      0.1211
C(year)[T.1980]          1.3625     0.0162     83.903     0.0000      1.3306      1.3943
C(year)[T.1981]          1.3400     0.1452     9.2307     0.0000      1.0554      1.6247
C(year)[T.1982]          1.3567     0.1451     9.3481     0.0000      1.0722      1.6412
C(year)[T.1983]          1.3729     0.1452     9.4561     0.0000      1.0882      1.6575
C(year)[T.1984]          1.4468     0.1452     9.9617     0.0000      1.1621      1.7316
C(year)[T.1985]          1.4122     0.1451     9.7315     0.0000      1.1277      1.6967
C(year)[T.1986]          1.4281     0.1451     9.8404     0.0000      1.1435      1.7126
C(year)[T.1987]          1.4529     0.1452     10.006     0.0000      1.1682      1.7376
C(year)[T.1981]:educ     0.0116     0.0123     0.9448     0.3448     -0.0125      0.0356
C(year)[T.1982]:educ     0.0148     0.0123     1.2061     0.2279     -0.0093      0.0388
C(year)[T.1983]:educ     0.0171     0.0123     1.3959     0.1628     -0.0069      0.0412
C(year)[T.1984]:educ     0.0166     0.0123     1.3521     0.1764     -0.0075      0.0406
C(year)[T.1985]:educ     0.0237     0.0123     1.9316     0.0535     -0.0004      0.0478
C(year)[T.1986]:educ     0.0274     0.0123     2.2334     0.0256      0.0033      0.0515
C(year)[T.1987]:educ     0.0304     0.0123     2.4798     0.0132      0.0064      0.0545
========================================================================================

F-test for Poolability: 8.0932
P-value: 0.0000
Distribution: F(544,3799)

Included effects: Entity

### Exemplo 14.4 - Uma equação de Salários com dados em painel

In [83]:
# Importando os dados
wagepan = woo.dataWoo("wagepan")
wagepan.head()

,nr,year,agric,black,bus,construc,ent,exper,fin,hisp,poorhlth,hours,manuf,married,min,nrthcen,nrtheast,occ1,occ2,occ3,occ4,occ5,occ6,occ7,occ8,occ9,per,pro,pub,rur,south,educ,tra,trad,union,lwage,d81,d82,d83,d84,d85,d86,d87,expersq
0,13,1980,0,0,1,0,0,1,0,0,0,2672,0,0,0,0,1,0,0,0,0,0,0,0,0,1,0,0,0,0,0,14,0,0,0,1.197540,0,0,0,0,0,0,0,1
1,13,1981,0,0,0,0,0,2,0,0,0,2320,0,0,0,0,1,0,0,0,0,0,0,0,0,1,1,0,0,0,0,14,0,0,1,1.853060,1,0,0,0,0,0,0,4
2,13,1982,0,0,1,0,0,3,0,0,0,2940,0,0,0,0,1,0,0,0,0,0,0,0,0,1,0,0,0,0,0,14,0,0,0,1.344462,0,1,0,0,0,0,0,9
3,13,1983,0,0,1,0,0,4,0,0,0,2960,0,0,0,0,1,0,0,0,0,0,0,0,0,1,0,0,0,0,0,14,0,0,0,1.433213,0,0,1,0,0,0,0,16
4,13,1984,0,0,0,0,0,5,0,0,0,3071,0,0,0,0,1,0,0,0,0,1,0,0,0,0,1,0,0,0,0,14,0,0,0,1.568125,0,0,0,1,0,0,0,25

In [84]:
# Ajustando os índices (ano e identificador)
wagepan = wagepan.set_index(['nr', 'year'], drop=False)

##### MQO Agrupado

In [85]:
model_pooled = plm.PooledOLS.from_formula(formula='lwage ~ educ + black + hisp + exper + expersq + married + union + C(year)', data=wagepan)
results_pooled = model_pooled.fit()

# Exibindo resultados
print(results_pooled.summary)

                          PooledOLS Estimation Summary
================================================================================
Dep. Variable:                  lwage   R-squared:                        0.1893
Estimator:                  PooledOLS   R-squared (Between):              0.2066
No. Observations:                4360   R-squared (Within):               0.1692
Date:                Mon, Jan 27 2025   R-squared (Overall):              0.1893
Time:                        16:51:42   Log-likelihood                   -2982.0
Cov. Estimator:            Unadjusted
                                        F-statistic:                      72.459
Entities:                         545   P-value                           0.0000
Avg Obs:                       8.0000   Distribution:                 F(14,4345)
Min Obs:                       8.0000
Max Obs:                       8.0000   F-statistic (robust):             3381.6
                                        P-value                           0.0000
Time periods:                       8   Distribution:                 F(14,4345)
Avg Obs:                       545.00
Min Obs:                       545.00
Max Obs:                       545.00

                                Parameter Estimates
===================================================================================
                 Parameter  Std. Err.     T-stat    P-value    Lower CI    Upper CI
-----------------------------------------------------------------------------------
educ                0.0913     0.0052     17.442     0.0000      0.0811      0.1016
black              -0.1392     0.0236    -5.9049     0.0000     -0.1855     -0.0930
hisp                0.0160     0.0208     0.7703     0.4412     -0.0248      0.0568
exper               0.0672     0.0137     4.9095     0.0000      0.0404      0.0941
expersq            -0.0024     0.0008    -2.9413     0.0033     -0.0040     -0.0008
married             0.1083     0.0157     6.8997     0.0000      0.0775      0.1390
union               0.1825     0.0172     10.635     0.0000      0.1488      0.2161
C(year)[T.1980]     0.0921     0.0783     1.1761     0.2396     -0.0614      0.2455
C(year)[T.1981]     0.1504     0.0838     1.7935     0.0730     -0.0140      0.3148
C(year)[T.1982]     0.1548     0.0893     1.7335     0.0831     -0.0203      0.3299
C(year)[T.1983]     0.1541     0.0944     1.6323     0.1027     -0.0310      0.3391
C(year)[T.1984]     0.1825     0.0990     1.8437     0.0653     -0.0116      0.3766
C(year)[T.1985]     0.2013     0.1031     1.9523     0.0510     -0.0008      0.4035
C(year)[T.1986]     0.2340     0.1068     2.1920     0.0284      0.0247      0.4433
C(year)[T.1987]     0.2659     0.1100     2.4166     0.0157      0.0502      0.4816
===================================================================================

##### Efeitos aleatórios

In [86]:
model_re = plm.RandomEffects.from_formula(formula='lwage ~ educ + black + hisp + exper + expersq + married + union + C(year)', data=wagepan)
results_re = model_re.fit()

# Exibindo resultados
print(results_re.summary)

                        RandomEffects Estimation Summary
================================================================================
Dep. Variable:                  lwage   R-squared:                        0.1806
Estimator:              RandomEffects   R-squared (Between):              0.1853
No. Observations:                4360   R-squared (Within):               0.1799
Date:                Mon, Jan 27 2025   R-squared (Overall):              0.1828
Time:                        16:51:50   Log-likelihood                   -1622.5
Cov. Estimator:            Unadjusted
                                        F-statistic:                      68.409
Entities:                         545   P-value                           0.0000
Avg Obs:                       8.0000   Distribution:                 F(14,4345)
Min Obs:                       8.0000
Max Obs:                       8.0000   F-statistic (robust):             846.19
                                        P-value                           0.0000
Time periods:                       8   Distribution:                 F(14,4345)
Avg Obs:                       545.00
Min Obs:                       545.00
Max Obs:                       545.00

                                Parameter Estimates
===================================================================================
                 Parameter  Std. Err.     T-stat    P-value    Lower CI    Upper CI
-----------------------------------------------------------------------------------
educ                0.0919     0.0107     8.5744     0.0000      0.0709      0.1129
black              -0.1394     0.0480    -2.9054     0.0037     -0.2334     -0.0453
hisp                0.0217     0.0428     0.5078     0.6116     -0.0622      0.1057
exper               0.1058     0.0154     6.8706     0.0000      0.0756      0.1361
expersq            -0.0047     0.0007    -6.8623     0.0000     -0.0061     -0.0034
married             0.0638     0.0168     3.8035     0.0001      0.0309      0.0967
union               0.1059     0.0179     5.9289     0.0000      0.0709      0.1409
C(year)[T.1980]     0.0234     0.1514     0.1546     0.8771     -0.2735      0.3203
C(year)[T.1981]     0.0638     0.1601     0.3988     0.6901     -0.2500      0.3777
C(year)[T.1982]     0.0543     0.1690     0.3211     0.7481     -0.2770      0.3856
C(year)[T.1983]     0.0436     0.1780     0.2450     0.8065     -0.3054      0.3926
C(year)[T.1984]     0.0664     0.1871     0.3551     0.7225     -0.3003      0.4332
C(year)[T.1985]     0.0811     0.1961     0.4136     0.6792     -0.3034      0.4656
C(year)[T.1986]     0.1152     0.2052     0.5617     0.5744     -0.2870      0.5175
C(year)[T.1987]     0.1583     0.2143     0.7386     0.4602     -0.2618      0.5783
===================================================================================

##### Efeitos fixos

In [87]:
model_fe = plm.PanelOLS.from_formula(formula='lwage ~ expersq + married + union + C(year) + EntityEffects', data=wagepan)
results_fe = model_fe.fit()

# Exibindo resultados
print(results_fe.summary)

                          PanelOLS Estimation Summary
================================================================================
Dep. Variable:                  lwage   R-squared:                        0.1806
Estimator:                   PanelOLS   R-squared (Between):             -0.0052
No. Observations:                4360   R-squared (Within):               0.1806
Date:                Mon, Jan 27 2025   R-squared (Overall):              0.0807
Time:                        16:51:50   Log-likelihood                   -1324.8
Cov. Estimator:            Unadjusted
                                        F-statistic:                      83.851
Entities:                         545   P-value                           0.0000
Avg Obs:                       8.0000   Distribution:                 F(10,3805)
Min Obs:                       8.0000
Max Obs:                       8.0000   F-statistic (robust):             8850.2
                                        P-value                           0.0000
Time periods:                       8   Distribution:                 F(10,3805)
Avg Obs:                       545.00
Min Obs:                       545.00
Max Obs:                       545.00

                                Parameter Estimates
===================================================================================
                 Parameter  Std. Err.     T-stat    P-value    Lower CI    Upper CI
-----------------------------------------------------------------------------------
expersq            -0.0052     0.0007    -7.3612     0.0000     -0.0066     -0.0038
married             0.0467     0.0183     2.5494     0.0108      0.0108      0.0826
union               0.0800     0.0193     4.1430     0.0000      0.0421      0.1179
C(year)[T.1980]     1.4260     0.0183     77.748     0.0000      1.3901      1.4620
C(year)[T.1981]     1.5772     0.0216     72.966     0.0000      1.5348      1.6196
C(year)[T.1982]     1.6790     0.0265     63.258     0.0000      1.6270      1.7310
C(year)[T.1983]     1.7805     0.0333     53.439     0.0000      1.7151      1.8458
C(year)[T.1984]     1.9161     0.0417     45.982     0.0000      1.8344      1.9978
C(year)[T.1985]     2.0435     0.0515     39.646     0.0000      1.9424      2.1446
C(year)[T.1986]     2.1915     0.0630     34.771     0.0000      2.0679      2.3151
C(year)[T.1987]     2.3510     0.0762     30.867     0.0000      2.2017      2.5004
===================================================================================

F-test for Poolability: 9.1568
P-value: 0.0000
Distribution: F(544,3805)

Included effects: Entity